server:
  port: 8008

spring:
  application:
    name: medicalnow-backend
  datasource:
    platform: mysql
    url: jdbc:mysql://34.123.143.183:3306/medicalnow
    username: root
    password: 12345678
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update

medicalnow:
  security:
    salt: qwertyuiop
    secretJwt: 1234567890
