server:
  port: 8008

spring:
  application:
    name: medicalnow-backend
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/medicalnow
    username: root
    password: 12345678
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver

medicalnow:
  security:
    salt: qwertyuiop
    secretJwt: 1234567890
