### Mensaje del paciente al doctor
### POST http://localhost:8008/api/v1/chat/send/message/patient/{userId}

POST http://localhost:8008/api/v1/chat/send/message/patient/1
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA1MTM4NzMyfQ.wD2HcorhBJqMHkblVpY8iQcNISEm9m57gxbrYUM2YCs
Content-Type: application/json
Accept: application/json

{
  "doctorSpecialtyId": "24",
  "message": "Doctor buenos dias, mi hijo tiene un dolor de cabeza muy fuerte."
}

### Mensaje del doctor al paciente
### POST http://localhost:8008/api/v1/chat/send/message/doctor/{userId}

POST http://localhost:8008/api/v1/chat/send/message/doctor/25
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA1MTM4NzMyfQ.wD2HcorhBJqMHkblVpY8iQcNISEm9m57gxbrYUM2YCs
Content-Type: application/json
Accept: application/json

{
  "consultId": "1",
  "message": "Buenos dias, que temperatura tiene su hijo?"
}

### Mostrar todos los mensajes de una consulta al paciente
### GET http://localhost:8008/api/v1/chat/patient/{consultId}/messages

GET http://localhost:8008/api/v1/chat/patient/1/messages
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA1MTM4NzMyfQ.wD2HcorhBJqMHkblVpY8iQcNISEm9m57gxbrYUM2YCs
Content-Type: application/json

{

}

### Mostrar todos los mensajes de una consulta al doctor
### GET http://localhost:8008/api/v1/chat/doctor/{consultId}/messages

GET http://localhost:8008/api/v1/chat/doctor/1/messages
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA1MTM4NzMyfQ.wD2HcorhBJqMHkblVpY8iQcNISEm9m57gxbrYUM2YCs
Content-Type: application/json

{

}

###