### Mostrar los mensajes PACIENTE
### GET http://localhost:8008/api/v1/chat/patient/{consultId}/messages

GET http://localhost:8008/api/v1/chat/patient/1/messages
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzMyIsInJvbGUiOiJQQVRJRU5UIiwiaXNzIjoiTWVkaWNhbG5vdyIsInR5cGUiOiJBVVRITiIsImV4cCI6MTYwNzAwNjMwMX0.4NuSGcMQRgTj6u9iLhmutBxEs3sRPYIMUkAnmI61yOM
Content-Type: application/json

{

}

### Mostrar los mensajes DOCTOR
### GET http://localhost:8008/api/v1/chat/doctor/{consultId}/messages
### NADA CAMBIO

GET http://localhost:8008/api/v1/chat/doctor/4/messages
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA1NzMxNTMzfQ.ZhS9CRZZKVPhTb3h5XA7x8YdMv7btv6bDQV4sMW_fWo
Content-Type: application/json

{

}

### Mensaje del paciente al doctor
### POST http://localhost:8008/api/v1/chat/send/message/{userId}

POST http://localhost:8008/api/v1/chat/send/message/33
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA2NDI4MTA1fQ.33iJeuFI2RGPCvaAjr6eVc9tMOHVfbnO95PxlOfkYYw
Content-Type: application/json
Accept: application/json

{
  "consultId": "10",
  "message": "Doctor buenos dias, me duele mucho el pecho y tengo taquicardias desde anoche."
}

### Obtener la imagen
### POST http://localhost:8008/api/v1/chat/send/message/{userId}

POST http://localhost:8008/api/v1/chat/get/{imageName}
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA1NzMxNTMzfQ.ZhS9CRZZKVPhTb3h5XA7x8YdMv7btv6bDQV4sMW_fWo
Content-Type: application/json
Accept: application/json

{
  "imageName": "4"
}

###