### Lista todas las consultas del paciente
### GET http://localhost:8008/api/v1/consults/patient/{userId}

GET http://localhost:8008/api/v1/consults/patient/1
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA1MTM4NzMyfQ.wD2HcorhBJqMHkblVpY8iQcNISEm9m57gxbrYUM2YCs
Content-Type: application/json
Accept: application/json

{

}

### Lista todas las consultas del doctor
### GET http://localhost:8008/api/v1/consults/doctor/{userId}

GET http://localhost:8008/api/v1/consults/doctor/25
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA1MTM4NzMyfQ.wD2HcorhBJqMHkblVpY8iQcNISEm9m57gxbrYUM2YCs
Content-Type: application/json
Accept: application/json

{

}

### Dar de alta a un paciente
### GET http://localhost:8008/api/v1/consults/discharge/{consultId}

POST http://localhost:8008/api/v1/consults/discharge/1
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA1MTM4NzMyfQ.wD2HcorhBJqMHkblVpY8iQcNISEm9m57gxbrYUM2YCs
Content-Type: application/json
Accept: application/json

{

}

###
