### Lista todas las consultas del paciente


GET http://localhost:8008/api/v1/consults/patient/1
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzMyIsInJvbGUiOiJQQVRJRU5UIiwiaXNzIjoiTWVkaWNhbG5vdyIsInR5cGUiOiJBVVRITiIsImV4cCI6MTYwNDg0OTc2Nn0.zdNNGEW4L_oj7MlC2aIlguL88Us6Zfwwqpa67kt_ddE
Content-Type: application/json
Accept: application/json

{

}

### Lista todas las consultas del doctor

GET http://localhost:8008/api/v1/consults/doctor/2
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzMyIsInJvbGUiOiJQQVRJRU5UIiwiaXNzIjoiTWVkaWNhbG5vdyIsInR5cGUiOiJBVVRITiIsImV4cCI6MTYwNDg1NTEwNH0.E-o_At0grje5J-0sx0SETVFI6n7c6ossz9iaOO2qyKI
Content-Type: application/json
Accept: application/json

{

}

###
