### Obtiene todas las historias medicas de un paciente
### GET http://localhost:8008/api/v1/medical_history/list/all/{userId}

GET http://localhost:8008/api/v1/medical_history/list/all/1
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA1NzUzMTAyfQ.aaGkPhrrd0ryuOGMczqpUt0VPNXy3epDXVmgb7Ce4n4
Content-Type: application/json
Accept: application/json

{

}

### Obtiene todas las consultas de una historia médica
### GET http://localhost:8008/api/v1/medical_history/{medicalHistoryId}/all/consults

GET http://localhost:8008/api/v1/medical_history/1/all/consults
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA1NzU3NzQxfQ.CDSWCbspeEmDbogdK7xm9v8Rln6nSi0giocVB9sbVM4
Content-Type: application/json
Accept: application/json

{

}

### Detalle de una consulta
### GET http://localhost:8008/api/v1/medical_history/{consultId}/detail

GET http://localhost:8008/api/v1/medical_history/1/detail
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA1NzU3NjEwfQ.C9rFTK6IVtygI-TblSzl2BDLqFH6OxNM73KL6hQc7rc
Content-Type: application/json
Accept: application/json

{

}

###

