### Obtiene todas las consultas que tienen prescripciones
### GET http://localhost:8008/api/v1/prescription/consults/{userId}

GET http://localhost:8008/api/v1/prescription/consults/1
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA2OTUyNDg3fQ.INwTCl0BcFLfqMfWfYHxW4f7iWr0Yds2o4Ye5NsOntA
Content-Type: application/json
Accept: application/json

{

}

### Obtiene todas las prescripciones de una consulta
### GET http://localhost:8008/api/v1/prescription/{consultId}/all

GET http://localhost:8008/api/v1/prescription/1/all
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA2OTUyNDg3fQ.INwTCl0BcFLfqMfWfYHxW4f7iWr0Yds2o4Ye5NsOntA
Content-Type: application/json
Accept: application/json

{

}

### Obtiene los detalles de la prescripcion de un paciente
### GET http://localhost:8008/api/v1/prescription/{prescriptionId}/detail

GET http://localhost:8008/api/v1/prescription/1/detail
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA2ODI5NTU1fQ.vYBsnuJ6DFZTyIM6Yed9nU59anI6qqlaZ6N8H70yXiM
Content-Type: application/json
Accept: application/json

{

}

### Agrega descripción y productos a una prescripción
### POST http://localhost:8008/api/v1/prescription/4/add/detail

POST http://localhost:8008/api/v1/prescription/4/add/detail
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA2ODI5OTU2fQ.A8Mki8d9DgFdItUBWv4QtJtoJnygGA7m5x8kJqP1OzY
Content-Type: application/json
Accept: application/json

{
  "description": "Debe hacer dieta una semana. No comer gluten. Debe tomar las pastillas recetadas por una semana.",
  "prescription_detail": [
    {
    "productName": "Glutagen",
    "productDetail": "Tomar una pastilla cada 8 horas",
    "productQtty": "10 pastillas"
  },
  {
    "productName": "Paracetamol",
    "productDetail": "Tomar en caso de dolor de cabeza, una cada dia.",
    "productQtty": "5 pastillas."
  }
  ]
}

###