### Todas las consultas que tienen prescripciones
### GET http://localhost:8008/api/v1/prescription/consults/{userId}

GET http://localhost:8008/api/v1/prescription/consults/1
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA1NDAzMTI3fQ.7fK4tluuSUHmPjJQ_jo0HmlBGOTci4GePE06m5ku0Qs
Content-Type: application/json
Accept: application/json

{

}

### Todas las prescripciones de una consulta
### GET http://localhost:8008/api/v1/prescription/{consultId}/all

GET http://localhost:8008/api/v1/prescription/1/all
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA1NDAzMTI3fQ.7fK4tluuSUHmPjJQ_jo0HmlBGOTci4GePE06m5ku0Qs
Content-Type: application/json
Accept: application/json

{

}

### Los detalles de la prescripcion de un paciente
### GET http://localhost:8008/api/v1/prescription/{prescriptionId}/detail

GET http://localhost:8008/api/v1/prescription/1/detail
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlBBVElFTlQiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA1NDAzMTI3fQ.7fK4tluuSUHmPjJQ_jo0HmlBGOTci4GePE06m5ku0Qs
Content-Type: application/json
Accept: application/json

{

}

###
