### Registrar a un paciente

POST http://localhost:8008/api/v1/patient/registry
Content-Type: application/json
Accept: application/json

{
  "firstName": "Ariel",
  "firstSurname": "Colque",
  "secondSurname": "Herrera",
  "birthDate": "1998-07-25",
  "email": "acolque@gmail.com",
  "password": "12345",
  "phoneNumber": "7812212"
}

###



