### Registrar a un paciente

POST http://localhost:8008/api/v1/user/registry
Content-Type: application/json
Accept: application/json

{
  "idNumber": "4930112",
  "firstName": "Camila",
  "firstSurname": "Gardeazabal",
  "secondSurname": "Cruz",
  "birthDate": "1989/12/24",
  "city": "La Paz",
  "email": "cgc@gmail.com",
  "password": "12345",
  "phoneNumber": "67288172"
}

###



