### Registrar a un paciente

POST http://localhost:8008/api/v1/user/registry
Content-Type: application/json
Accept: application/json

{
  "idNumber": "2055599",
  "firstName": "Claudia",
  "firstSurname": "Costa",
  "secondSurname": "Salinas",
  "birthDate": "1995/10/14",
  "city": "La Paz",
  "email": "ccosta@gmail.com",
  "password": "12345",
  "phoneNumber": "6753843"
}

###



