### Login

POST http://localhost:8008/api/v1/security/login
Content-Type: application/json
Accept: application/json

{
  "email": "acolque@gmail.com",
  "password": "12345"
}

### Refresh de tokens

POST http://localhost:8008/api/v1/security/refresh
Content-Type: application/json
Accept: application/json

{
  "refreshToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoiTWVkaWNhbG5vdyIsInR5cGUiOiJSRUZSRVNIIiwiZXhwIjoxNjA0Njk3NzU0fQ.xg7VxK4AO2hcIM2d1ZBLWWvCeRCKcC4JnDbBRV50uLo"
}

###