### Login

POST http://localhost:8008/api/v1/security/login
Content-Type: application/json
Accept: application/json

{
  "email": "mcardozo@gmail.com",
  "password": "12345"
}

### Refresh de tokens

POST http://localhost:8008/api/v1/security/refresh
Content-Type: application/json
Accept: application/json

{
  "refreshToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoiTWVkaWNhbG5vdyIsInR5cGUiOiJSRUZSRVNIIiwiZXhwIjoxNjA1NjY4MjE2fQ.fCYNbKPEFuXORZH0_I9Lyeb2VvBin5JQS2BVbZJrMvI"
}

###