### Todas las especialidades

GET http://localhost:8008/api/v1/specialties
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzMyIsInJvbGUiOiJQQVRJRU5UIiwiaXNzIjoiTWVkaWNhbG5vdyIsInR5cGUiOiJBVVRITiIsImV4cCI6MTYwNDcwOTA4N30.sWZzgq8WrpyZMWGKVz3FQ52PNjeHN_9oYSmwgxwqaDY
Content-Type: application/json
Accept: application/json

{

}

### Todos los medicos generales

GET http://localhost:8008/api/v1/specialties/general_medicine
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzMyIsInJvbGUiOiJQQVRJRU5UIiwiaXNzIjoiTWVkaWNhbG5vdyIsInR5cGUiOiJBVVRITiIsImV4cCI6MTYwNDcxMjE1NX0.tDkr5_RnHSqlDymtWRN4C5jPiyiStEbBAqen3iRKlZs
Content-Type: application/json
Accept: application/json

{

}

### Todos los doctores de una especialidad

GET http://localhost:8008/api/v1/specialties/2
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzMyIsInJvbGUiOiJQQVRJRU5UIiwiaXNzIjoiTWVkaWNhbG5vdyIsInR5cGUiOiJBVVRITiIsImV4cCI6MTYwNDcxMjE1NX0.tDkr5_RnHSqlDymtWRN4C5jPiyiStEbBAqen3iRKlZs
Content-Type: application/json
Accept: application/json

{

}

###
