### Obtener el avatar del usuario

GET http://localhost:8008/api/v1/user/1
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmZWF0dXJlcyI6WyJNRURJQ0FMX0hJU1RPUllfTUFOQUdNRU5UIiwiUFJFU0NSSVBUSU9OX01BTkFHTUVOVCIsIlNFTkRfUEhPVE9TIl0sInN1YiI6IjEiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA0MzQ5MjcxfQ.Z4QOa34G-UUuNHz3jfGCzo8r7n5MZ-QUPsTQ95htoEo
Content-Type: application/json
Accept: application/json

{

}

###

GET http://localhost:8008/api/v1/user/config/1
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmZWF0dXJlcyI6WyJNRURJQ0FMX0hJU1RPUllfTUFOQUdNRU5UIiwiUFJFU0NSSVBUSU9OX01BTkFHTUVOVCIsIlNFTkRfUEhPVE9TIl0sInN1YiI6IjEiLCJpc3MiOiJNZWRpY2Fsbm93IiwidHlwZSI6IkFVVEhOIiwiZXhwIjoxNjA0MzUwMjQwfQ.Mt2tqc4zZ_ZIPANyWf_1NXsxZ4HvrhUdK4BmDv0jTNE
Content-Type: application/json
Accept: application/json

{

}

###